name: dlis-writer
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - flake8
  - mypy
  - pytest
  - numpy
  - h5py
  - progressbar2
  - coloredlogs
  - typing_extensions
  - pip
  - pandas  # for reading data from csv and xls(x) files, only used in file_format_formatter subpackage
  - pytz
  - pip:
      - dlisio
      - lasio   # for reading data from LAS files, only used in file_format_formatter subpackage
