[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dlis-writer"
version = "0.0.8"
authors = [
  { name="Dominika Dlugosz", email="dominika.dlugosz@wellid.no" },
  { name="Kamil Grunwald", email="kamil.grunwald@wellid.no" },
  { name = "Omer Faruk Sari" }
]
description = "A package for creating DLIS files."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "flake8",
  "mypy",
  "pytest",
  "numpy",
  "h5py",
  "progressbar2",
  "coloredlogs",
  "typing_extensions",
  "dlisio"
]
[project.urls]
"Homepage" = "https://github.com/well-id/dlis-writer"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["py.typed"]
